name: Deploy to cPanel via FTPS

on:
  push:
    branches: [ main ]   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for collectstatic
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static assets
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
          SECRET_KEY: dummy-secret-for-build
          DEBUG: "0"
          ALLOWED_HOSTS: "sub.example.com"
        run: |
          python manage.py collectstatic --noinput

      - name: Prepare Passenger restart
        run: |
          mkdir -p tmp
          date > tmp/restart.txt

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          # Update this path to your app root shown in cPanel "Application root"
          server-dir: /home/youruser/apps/mysite/
          exclude: |
            **/.git*
            **/.github/**
            **/venv/**
            **/__pycache__/**
            **/*.sqlite3
